ARG XDEBUG_VERSION="xdebug-3.4.7"

# Use the official PHP image as a base image
FROM php:8.2-apache AS dev

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    zip \
    unzip \
    git \
    curl \
    libzip-dev \
    libonig-dev \
    libssl-dev \
    pkg-config \
    && docker-php-ext-install mbstring zip \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN a2enmod rewrite
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN yes | pecl install ${XDEBUG_VERSION} \
    docker-php-ext-enable xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini


# Set working directory
WORKDIR /var/www/html

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy the existing application directory contents to the working directory
COPY . /var/www/html

RUN chown -R www-data:www-data /var/www

# Install project dependencies
RUN composer install --optimize-autoloader
