sonar.projectKey=library-app-auth
sonar.projectName=library-app-auth

sonar.sources=app
sonar.tests=tests

sonar.php.coverage.reportPaths=storage/logs/clover.xml

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**

sonar.sourceEncoding=UTF-8
