FROM php:8.4-apache AS dev

RUN apt-get update && apt-get install -y \
    build-essential \
    zip \
    unzip \
    git \
    iputils-ping \
    curl \
    libzip-dev \
    libonig-dev \
    libssl-dev \
    pkg-config \
    librdkafka-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install mbstring zip \
    && pecl install mongodb \
    && pecl install rdkafka \
    && docker-php-ext-enable mongodb rdkafka

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN a2enmod rewrite
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN pecl install xdebug-3.4.7 \
    && docker-php-ext-enable xdebug

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

COPY composer.json composer.lock ./

RUN composer install --optimize-autoloader --no-scripts

COPY . /var/www/html

COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN chown -R www-data:www-data /var/www/html
