<?php

namespace App\DTO;

/**
 * Represents the JWT payload generated by the authentication service.
 */
readonly class JwtPayloadDTO
{
    /**
     * @param string $issuer
     * @param string $audience
     * @param string $memberCardUuid
     */
    public function __construct(
        public string $issuer,
        public string $audience,
        public string $memberCardUuid
    )
    {
    }

    /**
     * @return array<string, string>
     */
    public function toArray(): array
    {
        return [
            'iss' => $this->issuer,
            'aud' => $this->audience,
            'member_card_uuid' => $this->memberCardUuid,
        ];
    }
}
